---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for SSH access to the EC2 instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: bbkey.pem
  InstType:
    Description: Instance Type for EC2 instances
    Type: String
    Default: t2.micro
  CidrBlock:
    Description: IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.1.0.0/16
  SubnetCIDR:
    Description: IP range (CIDR notation) for the subnet in the Availability Zone a
    Type: String
    Default: 10.1.1.0/24

Resources:
  iacVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock:
        Ref: CidrBlock
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: c_iac_VPC
      - Key: created_by
        Value: Camilo Ruiz
  iacSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock:
        Ref: SubnetCIDR
      Tags:
      - Key: Name
        Value: c_iac_subnet
      - Key: created_by
        Value: Camilo Ruiz
      VpcId:
        Ref: iacVPC
  iacSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: c_iac_sg
      GroupDescription: Security group for Application Instance
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
      VpcId:
        Ref: iacVPC
      Tags:
      - Key: Name
        Value: c_iac_SG
      - Key: created_by
        Value: Camilo Ruiz
  iacInst:
    Type: AWS::EC2::Instance
    DeletionPolicy: Delete
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-b70554c8
      InstanceType: !Ref InstType
      KeyName: !Ref KeyName
      NetworkInterfaces:
      - AssociatePublicIpAddress: 'true'
        DeviceIndex: '0'
        GroupSet:
        - Ref: iacSG
        SubnetId:
          Ref: iacSubnet
      Tags:
      - Key: Name
        Value: c_iac_instance
      - Key: created_by
        Value: Camilo Ruiz

Outputs:
  VPC:
    Description: Referenced to the created VPC
    Value: !Ref iacVPC
  Subnet:
    Description: Referenced to the created VPC
    Value: !Ref iacSubnet
  SecurityGroup:
    Description: Referenced to the created VPC
    Value: !Ref iacSG
  Instance:
    Description: Referenced to the created VPC
    Value: !Ref iacInst
  